name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true
    outputs:
      tag: ${{steps.tag.outputs.tag}}

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Tags
        id: tag
        run: |
          tag=$(bash .github/scripts/getTags.sh)
          echo "tag $tag"
          echo tag=$tag >> $GITHUB_OUTPUT

      - name: Set up Python all python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: Install Python Virtual ENV
        run: pip3 install virtualenv

        # Caching Dependencies using actions/cache@v2
      - name: Setup Virtual env
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Activate and Install Dependencies into Virtual env
        run: python -m venv venv && source venv/bin/activate &&
          pip3 install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      # Install all the app dependencies
      - name: Install dependencies
        run: pip3 install -r requirements.txt

      # Build the app and run tests
      - name: Build and Run Test
        run: . venv/bin/activate && pytest

      # use the highest level of compression to create api.zip archive.
      - name: Create Zipfile archive of Dependencies
        run: |
          cd ./venv/lib/python3.7/site-packages
          zip -r9 ../../../../api.zip .
          cd ../../../../

      # update api.zip with ./app contents
      - name: Add App to Zipfile
        run: |
          cd ./app
          zip -g ../api.zip -r .
          cd ../
          mv api.zip api-v${{steps.tag.outputs.tag}}.zip

        # Upload api.zip to GitHub server as an artifact using actions/upload-artifact@v2
        # the next job to retrieve back the artifact file
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api-v${{steps.tag.outputs.tag}}.zip

  continuous-deployment:
    runs-on: ubuntu-latest
    # job will only run when the continuous-integration build successfully completes
    needs: [continuous-integration]
    # Check if current branch is main
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update lambda version in terraform file
        run: |
          sed -i "s/api.zip/api-v${{needs.continuous-integration.outputs.tag}}.zip/g" .github/terraform/variables.tf

      - name: Download Lambda api.zip
        uses: actions/download-artifact@v2
        with:
          name: api

      - name: Upload to S3
        run: aws s3 cp api-v${{needs.continuous-integration.outputs.tag}}.zip s3://crommie-s3/api-v${{needs.continuous-integration.outputs.tag}}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: .github/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KEY_SECRET }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Terraform Validate and Plan
        run: |
          terraform validate -no-color
          terraform plan -no-color
        working-directory: .github/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KEY_SECRET }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Terraform Apply and Deploy Lambda
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: .github/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KEY_SECRET }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Clean repo
        run: git clean -f

      - name: Create and push tag
        run: |
          git tag ${{needs.continuous-integration.outputs.tag}} || echo "tag already exists"
          git push --tags
        env:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
